nf_core_version: 2.14.1
repository_type: pipeline
template:
  name: readmapping
lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-readmapping_logo_light.png
    - conf/igenomes.config
    - docs/images/nf-core-readmapping_logo_dark.png
    - docs/images/nf-core-readmapping_logo_light.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - docs/README.md
    - lib/NfcoreTemplate.groovy
    - .github/workflows/branch.yml
    - .gitignore
    - .github/workflows/linting.yml
    - .github/PULL_REQUEST_TEMPLATE.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
      - params.vector_db
  multiqc_config: False
