contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #readmapping channel"
    url: https://nfcore.slack.com/channels/readmapping
    about: Discussion about the nf-core/readmapping pipeline
