name: Fix linting from a comment
on:
  issue_comment:
    types: [created]

jobs:
  fix-linting:
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, '@sanger-tolsoft fix linting') &&
      github.repository == 'sanger-tol/readmapping'
    runs-on: ubuntu-latest
    steps:
      # Use the @sanger-tolsoft token to check out so we can push later
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.sangertolsoft_access_token }}

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.sangertolsoft_access_token }}

      - uses: actions/setup-node@v3

      - name: Install Prettier
        run: npm install -g prettier @prettier/plugin-php

      # Check that we actually need to fix something
      - name: Run 'prettier --check'
        id: prettier_status
        run: |
          if prettier --check ${GITHUB_WORKSPACE}; then
            echo "result=pass" >> $GITHUB_OUTPUT
          else
            echo "result=fail" >> $GITHUB_OUTPUT
          fi

      - name: Run 'prettier --write'
        if: steps.prettier_status.outputs.result == 'fail'
        run: prettier --write ${GITHUB_WORKSPACE}

      - name: Commit & push changes
        id: commit-and-push
        if: steps.pre-commit.outcome == 'failure'
        run: |
          git config user.email "105875386+sanger-tolsoft@users.noreply.github.com"
          git config user.name "sanger-tolsoft"
          git config push.default upstream
          git add .
          git status
          git commit -m "[automated] Fix code linting"
          git push

      - name: react if linting errors were fixed
        id: react-if-fixed
        if: steps.commit-and-push.outcome == 'success'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: hooray

      - name: react if linting errors were not fixed
        if: steps.commit-and-push.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: confused

      - name: react if linting errors were not fixed
        if: steps.commit-and-push.outcome  == 'failure'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            @${{ github.actor }} I tried to fix the linting errors, but it didn't work. Please fix them manually.
            See [CI log](https://github.com/nf-core/readmapping/actions/runs/${{ github.run_id }}) for more details.
