name: nf-core Sanger LSF full size tests

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run LSF full size tests
    runs-on: ubuntu-latest
    steps:
      - name: Launch workflow via tower
        uses: nf-core/tower-action@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          pipeline: ${{ github.repository }}
          revision: ${{ github.sha }}
          workdir: ${{ secrets.TOWER_WORKDIR_PARENT }}/work/readmapping/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "${{ secrets.TOWER_WORKDIR_PARENT }}/results/readmapping/results-${{ github.sha }}",
            }
          profiles: test_full,sanger,singularity
